name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp pytest
      - name: Run tests
        run: |
          pytest -q
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/maxwelldps/sip-bridge:${{ github.sha }} .
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/maxwelldps/sip-bridge:${{ github.sha }}
            ghcr.io/maxwelldps/sip-bridge:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
